// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPayManager.Crosscutting.Database;

#nullable disable

namespace PicPayManager.Migrations
{
    [DbContext(typeof(PicPaySimplificadoContext))]
    [Migration("20260504151628_AddCpfIndex")]
    partial class AddCpfIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PicPayManager.Transference.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TransactionDestination", "PicPayManager.Transference.Transactions.TransactionDestination#TransactionDestination", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("TransactionDestination");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TransactionOrigin", "PicPayManager.Transference.Transactions.TransactionOrigin#TransactionOrigin", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("TransactionOrigin");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TransferBalance", "PicPayManager.Transference.Transactions.TransferBalance#TransferBalance", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("_balance")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("TransferBalance");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("PicPayManager.UserAccounts.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cpf", "PicPayManager.UserAccounts.User.Cpf#Cpf", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnType("char(11)")
                                .HasColumnName("Cpf");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "PicPayManager.UserAccounts.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PicPayManager.UserAccounts.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("_value")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WalletBalance", "PicPayManager.UserAccounts.User.WalletBalance#WalletBalance", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("WalletBalance");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PicPayManager.Transference.Transactions", b =>
                {
                    b.HasOne("PicPayManager.UserAccounts.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PicPayManager.UserAccounts.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
