<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dataflow.Block.Livro.Tests\**\*.cs" />
    <EmbeddedResource Remove="Dataflow.Block.Livro.Tests\**\*" />
    <None Remove="Dataflow.Block.Livro.Tests\**\*" />
  </ItemGroup>

</Project>
