// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poc.WorkflowCore.Domain.Orchestration.Infrastructure;

#nullable disable

namespace Poc.WorkflowCore.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20260624142519_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poc.WorkflowCore.Domain.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RequestDate");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("State");

                    b.Property<DateTime?>("SuspensionEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SuspensionEndDate");

                    b.Property<DateTime?>("SuspensionStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SuspensionStartDate");

                    b.HasKey("Id");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Poc.WorkflowCore.Domain.Enrollment", b =>
                {
                    b.OwnsOne("Poc.WorkflowCore.Domain.Orchestration.Aggreates.Client", "Client", b1 =>
                        {
                            b1.Property<Guid>("EnrollmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ClientAddress");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ClientCpf");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ClientEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ClientName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ClientPhone");

                            b1.HasKey("EnrollmentId");

                            b1.ToTable("Enrollments");

                            b1.WithOwner()
                                .HasForeignKey("EnrollmentId");
                        });

                    b.Navigation("Client")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
